<!DOCTYPE html>
<html >
<head>
	<meta charset="UTF-8">
	<title>VetClick | Operatör Modülü</title>
	<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

	<?php
	$app = PSK_Application::getInstance();

	$app->layout->RenderStyleLinks();
	?>

	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
</head>
<body>

<?php
$app->layout->IncludeView();
$app->layout->RenderScriptLinks();
?>

</body>
</html>